### ISSUE TITLE
No results when executing Count(*) query in MySQL

### ISSUE THREAD

**Issue by juancarlis** [kristijanhusak/vim-dadbod-ui#141]
When executing for example: 
SELECT count(*) from some_table;

I get an output like: 
+----------+
| count(*)   |
+----------+
+-- 5 lines: +-----------------+ - - - - - - - - - - - - - -

With the result information hidden. If I copy the output and paste it I see the complete query result:
+----------+
| count(*)   |
+----------+
|       34      |
+----------+
mysql: [Warning] Using a password on the command line interface can be insecure.

Also I would like to get rid of the [Warning]

**Comment by kristijanhusak** [comment]
Your results are just folded. Add this to your vimrc:

```
autocmd FileType dbout setlocal nofoldenable
```

Regarding the warning, you will have to enter the db connection link differently, because if you enter password directly, mysql complains. I'm not sure how exactly to hide the warning, but if you do not add a password in connection string, it should prompt the password, and this should not appear.
