### ISSUE TITLE
Suggestion.

### ISSUE THREAD

**Issue by alalfakawma** [kristijanhusak/vim-dadbod-ui#4]
Hey, I think this is great and saves the hassle of opening a new tmux window just for doing stuff in the database. Can you make it so that we can just add the connection and select databases from inside the GUI? Or is there a better way to dynamically specify a database so I don't have to always add it to my vimrc. Thanks for this by the way.

**Comment by kristijanhusak** [comment]
Yeah adding it from the GUI could be the option, but i would have to save that config somewhere.

Currently you can solve this by having a project local vimrc (see `:help exrc`), add it to `.gitignore` and define the connections there. So once you open your project, you should have all your databases set up.

**Comment by skriems** [comment]
It would be awesome to leverage tpope's dotenv plugin as well and get connections from environment variables. Assuming that most projects use a .env file (if not only for docker-compose) anyway, you could use that to setup your db connections

**Comment by kristijanhusak** [comment]
@skriems i plan to do that. My only concern is that i don't have the name for the connection. I could probably extract it from the url.

**Comment by skriems** [comment]
@kristijanhusak I guess I would use a (optionally configurable) prefix for env variables which could default to `DBUI_`. The rest of it lowercased could become the name maybe

**Comment by kristijanhusak** [comment]
@skriems support for env variables was added. Check this part of readme: https://github.com/kristijanhusak/vim-dadbod-ui#databases

**Comment by skriems** [comment]
cool, that was fast @kristijanhusak :)
However I think this is not as flexible as users might need it to be. A project I'm working on currently has two db servers with the same db name, so this wouldn't work perfectly for me (actually I only have to connect to one, so...). Anyhow, I guess I would prefere extracting the name from the env variable instead of the connection string.
But this is cool stuff nevertheless :D

**Comment by kristijanhusak** [comment]
Unfortunately it's not possible to set env variable to anything other than a string. If it would accept some kind of array, that would be nice.
If i would parse something by the part of the env variable name, i would have to read all env variables. That's a bit too much.
If you need more than 1 connections, i would suggest to use project specific vimrc with `g:dbs`, put it in global gitignore, and you should be good to go. That's how I use it since i have a lot of connections set up.
This env variable is just a nice addition.

I also plan to add the initial suggestion of this issue, so that will also cover your case in a way.

**Comment by alalfakawma** [comment]
This is real sick. Thank you for the quick follow up.

**Comment by skriems** [comment]
hey alalfakawma,

so first of all I think there's a race condition in the loading order of dadbod-ui and dotenv.vim (I guess due to alphabetical loading of plugins?). The first time dadbod-ui tries to get information from the env, dotenv.vim hasn't populated values from the .env file yet - load another file and you should be good.

2nd, I think you have confused the `g:db_ui_env_variable_name` with the name of the database. If you don't want to use a prefix in your .env file, you can still use `g:db_ui_env_variable_url` but this needs to be the full URL to your database, i.e.
```
postgres://<user>:<password>@<host>:<port>/<db_name>
```
dadbod-ui then tries to extract the `<db_name>` as the name in the UI and only if it fails, you can use `g:db_ui_env_variable_name` to overwrite/specify one.

With this in mind, I suspect that you need to build a dedicated env variable in your .env file, because `DB_HOST` and `DB_DATABSE` usually only refert to parts of the whole string like above

**Comment by kristijanhusak** [comment]
@skriems is right for everything. For dotenv to load the env variables, some file must be opened to trigger it. I tried to go around it, but it's not doing the trick.

**Comment by kristijanhusak** [comment]
This feature is added. Check this part of readme:
https://github.com/kristijanhusak/vim-dadbod-ui#via-dbuiaddconnection-command

**Comment by alalfakawma** [comment]
Great job @kristijanhusak. Also, thanks for clearing things up @skriems. It now works. Great stuff.
