### ISSUE TITLE
See views and materialized views in the drawer

### ISSUE THREAD

**Issue by RRikor** [kristijanhusak/vim-dadbod-ui#86]
I work with PostgreSQL databases. Is there some hidden option to see views and materialized views in the drawer? I couldn't find this unfortunately.

**Comment by kristijanhusak** [comment]
It's not hidden, just not implemented. I plan to introduce it.

**Comment by kristijanhusak** [comment]
Materialized views are now included in the list of tables. Views should already be there, only materialized views were missing. Currently there is no way to distinguish between a table and a view, because that require changes in the rendering. That can be done separately. Let me know if it works for you.

**Comment by RRikor** [comment]
Works good, thanks for the quick update!
